# Generated by Django 3.1.2 on 2021-11-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0004_auto_20201111_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
